# https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          # Maintainer doesn't want to properly support non-beta releases and archived the repo
          - prettier@3.3.3
