name: Test

on:
  - pull_request
  - push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint

  Types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npx tsc

  Demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd test/demo-extension && npm ci
      - run: cd test/demo-extension && npm run demo:build
